services:
  portage-binhost:
    build:
      args:
        GIT_SHORT_SHA:
      context: Dockerfile.d/portage-binhost
    image: local.local/${PROJECT_UNIQUE_ID:-no-name}/portage-binhost:HEAD
    init: true
    ports:
      - 8080:80
    pull_policy: never

  # for testing
  portage:
    image: gentoo/portage
    volumes:
      - portage-data:/var/db/repos/gentoo
  stage3:
    command: sleep infinity
    environment:
      PORTAGE_BINHOST: http://binhost/var/cache/binpkgs
    image: gentoo/stage3
    init: true
    volumes:
      - portage-data:/var/db/repos/gentoo

  # for Prettier Code Formatter
  # ["INFO" - 00:00:00 AM] Attempted to determine module path from /path/to/the/project
  # ["ERROR" - 00:00:00 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
  # ["ERROR" - 00:00:00 AM] Cannot find module 'prettier' from '/path/to/the/project'
  workspace:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/workspace
    command:
      - zsh
      - --login
      - -c
      - |
        npm-check-updates --upgrade
        npm install
        npm audit fix
        sort-package-json
        sleep infinity
    init: true
    user: ${UID:-0}:${GID:-0}
    volumes:
      - .:/workspace
    working_dir: /workspace

version: "3.9"
volumes:
  portage-data:
